openapi: 3.0.0
info:
  title: Posts API
  version: 1.0.0
servers:
  - url: http://localhost:5000/
paths:
  /posts:
    post:
      summary: Creates a new post with message and location
      parameters:
        - in: body
          name: message
          description: The message to be posted
          required: true
          schema:
            type: object
            properties:
              message:
                type: string
              lat:
                type: number
              lon:
                type: number
      responses:
        '200':
          description: Post created successfully
        '400':
          description: Invalid latitude or longitude or missing required fields
        '500':
          description: An unknown error occurred

    get:
      summary: Get posts by location
      parameters:
        - in: query
          name: lat
          type: number
          required: true
          description: The latitude of the location
        - in: query
          name: lon
          type: number
          required: true
          description: The longitude of the location
        - in: query
          name: page
          type: integer
          required: false
          description: The page number for pagination (default 1)
      responses:
        '200':
          description: List of posts near the given location
        '400':
          description: Invalid page number or location parameters missing
        '500':
          description: An unknown error occurred

  /posts/generate:
    get:
      summary: Generates random posts
      parameters:
        - in: query
          name: num
          type: integer
          required: false
          description: The number of random posts to generate (default 10)
      responses:
        '200':
          description: Random posts generated successfully
        '400':
          description: Invalid number of posts
        '500':
          description: An unknown error occurred
